name: âš™ï¸ Exercise 3 - Deploy with Repo Variables
on:
  workflow_dispatch:

jobs:
  deploy:
    name: ğŸ§© Deploy with SERVICE_NAME
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: ğŸ Start Deployment
        shell: bash
        run: |
          echo "deploying: ${{ vars.SERVICE_NAME }}"
