name: ðŸ§  Exercise 4 - Auto Environment Deploy

on:
  push:
    branches:
      - '**'

jobs:
  deploy-dev:
    name: ðŸ§© Deploy to Dev (non-main)
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: ðŸš€ Deploying to Dev
        run: echo "deploy to ${{ github.environment }}"

  deploy-prod:
    name: ðŸš€ Deploy to Prod (main)
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: âš¡ Deploying to Prod
        run: echo "deploy to ${{ github.environment }}"
